version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:8.0
    ports:
      - 6379:6379
    networks:
      - n8n-network
    volumes:
      - ./redis_data:/data

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - n8n-network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  n8n-editor:
    container_name: n8n-editor
    image: n8nio/n8n:1.99.1
    restart: unless-stopped
    ports:
      - 5678:5678
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - n8n-network
    volumes:
      - ./n8n_data:/home/node/.n8n

  n8n-worker:
    container_name: n8n-worker
    image: n8nio/n8n:1.99.1
    restart: unless-stopped
    ports:
      - 5680:5678
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - n8n-network
    volumes:
      - ./n8n_data:/home/node/.n8n

  n8n-webhook:
    container_name: n8n-webhook
    image: n8nio/n8n:1.99.1
    restart: unless-stopped
    ports:
      - 5679:5678
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - n8n-network
    volumes:
      - ./n8n_data:/home/node/.n8n

networks:
  n8n-network:
    name: n8n-network
    driver: bridge